dnsmasq_config_dir: /etc/dnsmasq.d
# TODO: Generate these from the inventory.
dns_overrides:
  - { ip: 192.168.42.238, custom_dns: "main.knxcloud.io" }
  - { ip: 192.168.1.202, custom_dns: "pihole-primary.knxcloud.io" }
  - { ip: 192.168.3.254, custom_dns: "pihole-backup.knxcloud.io" }
  - { ip: 192.168.42.166, custom_dns: "ts.knxcloud.io" }
  - { ip: 192.168.42.57, custom_dns: "pve1.knxcloud.io" }
  - { ip: 192.168.42.239, custom_dns: "pve2.knxcloud.io" }
  - { ip: 192.168.1.217, custom_dns: "nas.knxcloud.io" }
  - { ip: 192.168.92.60, custom_dns: "dinos.sh" }
  - { ip: 192.168.60.44, custom_dns: "mon.knxcloud.io" }
  - { ip: 192.168.60.45, custom_dns: "infra.knxcloud.io" }
  - { ip: 192.168.42.122, custom_dns: "mqtt.knxcloud.io" }
