services:
  atuin:
    restart: unless-stopped
    image: ghcr.io/atuinsh/atuin:latest
    command: server start
    container_name: atuin
    env_file:
      - .env
    networks:
      - proxy
    volumes:
      - "./config:/config"
    ports:
      - 8888:8888
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "false"
      ATUIN_DB_URI: postgres://${ATUIN_DB_USERNAME}:${ATUIN_DB_PASSWORD}@atuin-db/${ATUIN_DB_NAME}
      RUST_LOG: info,atuin_server=debug
      TZ: ${TZ}
      PUID: 1000
      PGID: 1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.atuin.rule=Host(`atuin.${FULL_DOMAIN}`)"
      - "traefik.http.routers.atuin.entrypoints=https"
      - "traefik.http.routers.atuin.tls=true"
      - "traefik.http.services.atuin.loadbalancer.server.port=8888"
    depends_on:
      - atuin-db
  atuin-db:
    image: postgres:14
    restart: unless-stopped
    container_name: atuin-db
    networks:
      - proxy
    env_file:
      - .env
    volumes:
      - "./database:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      POSTGRES_DB: ${ATUIN_DB_NAME}
      TZ: ${TZ}
      PUID: 1000
      PGID: 1000

networks:
  proxy:
    external: true
